name: sundae
channels:
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - cudatoolkit=11.3
  - tqdm
  - toml
  - ipython
  - pip
  - pip:
    - tokenizers
    - datasets
    - transformers
    - x-transformers
    - ptpt=0.0.28
    - wandb
    - einops
